# Generated by Django 6.1.1 on 2026-09-15 15:07

import apps.core.services.upload_image
import apps.listing.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'region',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), apps.listing.models.validate_max_year])),
                ('mileage', models.PositiveIntegerField(help_text='Пробіг у кілометрах')),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=4)),
                ('condition_type', models.CharField(choices=[('new', 'Новий'), ('used', 'Вживаний')], max_length=20)),
                ('body_type', models.CharField(choices=[('sedan', 'Седан'), ('suv', 'Позашляховик'), ('hatchback', 'Хетчбек'), ('coupe', 'Купе'), ('wagon', 'Універсал'), ('pickup', 'Пікап'), ('van', 'Мінівен'), ('cabrio', 'Кабріолет')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гібрид'), ('electric', 'Електричний'), ('gas', 'Газ')], max_length=20)),
                ('transmission_type', models.CharField(choices=[('manual', 'Механіка'), ('automatic', 'Автомат'), ('robot', 'Робот'), ('cvt', 'Варіатор')], max_length=20)),
                ('drive_type', models.CharField(choices=[('fwd', 'Передній привід'), ('rwd', 'Задній привід'), ('awd', 'Повний привід')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(choices=[('usd', 'Долар США'), ('eur', 'Євро'), ('uah', 'Гривня')], max_length=10)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_uah', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('activate', 'Активне'), ('pending', 'На перевірці'), ('rejected', 'Відхилено'), ('blocked', 'Заблоковано'), ('inactive', 'Знято з продажу продавцем')], default='pending', max_length=10)),
                ('edit_count', models.PositiveIntegerField(default=0)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='cars.carmodel')),
                ('exchange_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.currencyrate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listing.region')),
            ],
            options={
                'db_table': 'listing',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.core.services.upload_image.upload_listing_image)),
                ('is_main', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_images', to='listing.listing')),
            ],
            options={
                'db_table': 'car_image',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price_usd'], name='listing_price_usd_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price_eur'], name='listing_price_eur_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price_uah'], name='listing_price_uah_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['year'], name='listing_year_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status'], name='listing_status_idx'),
        ),
    ]
