# Generated by Django 6.1.1 on 2026-09-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(choices=[('USD', 'Долар США'), ('EUR', 'Євро'), ('UAH', 'Гривня')], max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Активне'), ('pending', 'На перевірці'), ('rejected', 'Відхилено'), ('blocked', 'Заблоковано'), ('inactive', 'Знято з продажу продавцем')], default='pending', max_length=10),
        ),
        migrations.AlterModelTable(
            name='carimage',
            table='car_images',
        ),
    ]
