# Generated by Django 6.1.1 on 2026-09-15 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view', to='listing.listing')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listing_stats',
                'indexes': [models.Index(fields=['created_at'], name='listing_sta_created_1f5626_idx'), models.Index(fields=['listing'], name='listing_sta_listing_21d5a6_idx'), models.Index(fields=['listing', 'created_at'], name='listing_sta_listing_de4b1b_idx')],
            },
        ),
    ]
