# Generated by Django 6.1.1 on 2026-09-26 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmoderation',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingmoderation',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='listing.listing'),
        ),
        migrations.AddField(
            model_name='listingmoderation',
            name='moderation_action',
            field=models.CharField(choices=[('created', 'Створено'), ('edited', 'Відредаговано продавцем'), ('auto_approved', 'Автоматично схвалено'), ('auto_rejected', 'Автоматично відхилено'), ('manual_approved', 'Схвалено менеджером'), ('manual_rejected', 'Відхилено менеджером')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listingmoderation',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingmoderation',
            name='send_letter_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
