# Generated by Django 6.1.1 on 2026-09-26 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
        ('moderation', '0002_listingmoderation_comment_listingmoderation_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmoderation',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='listing.listing'),
        ),
        migrations.AlterField(
            model_name='listingmoderation',
            name='moderation_action',
            field=models.CharField(choices=[('created', 'Створено'), ('edited', 'Відредаговано продавцем'), ('auto_approved', 'Автоматично схвалено'), ('auto_rejected', 'Автоматично відхилено'), ('manual_approved', 'Схвалено менеджером'), ('manual_rejected', 'Відхилено менеджером')], max_length=20),
        ),
    ]
