# Generated by Django 5.0.6 on 2026-06-27 18:26

from django.db import migrations


def seed_roles_and_permissions(apps, schema_editor):
    """
    Створює початкові ролі та дозволи для системи.
    Викликається при застосуванні міграції.
    """
    Role = apps.get_model('users', 'Role')
    CustomPermission = apps.get_model('users', 'CustomPermission')
    RolePermissions = apps.get_model('users', 'RolePermissions')

    # ==================== ДОЗВОЛИ (PERMISSIONS) ====================

    # Дозволи для роботи з користувачами
    can_view_users = CustomPermission.objects.create(
        name='Can view users', codename='can_view_users'
    )
    can_view_user_by_id = CustomPermission.objects.create(
        name='Can view users by id', codename='can_view_user_by_id'
    )
    can_delete_user_by_id = CustomPermission.objects.create(
        name='Can delete users by id', codename='can_delete_user_by_id'
    )
    can_be_premium_user = CustomPermission.objects.create(
        name='Can be premium user', codename='can_be_premium_user'
    )
    can_view_own_account = CustomPermission.objects.create(
        name='Can view own account', codename='can_view_own_account'
    )
    can_update_own_account = CustomPermission.objects.create(
        name='Can update own account', codename='can_update_own_account'
    )
    can_delete_own_account = CustomPermission.objects.create(
        name='Can delete own account', codename='can_delete_own_account'
    )
    can_block_unblock_user = CustomPermission.objects.create(
        name='Can block unblock user', codename='can_block_unblock_user'
    )
    can_create_manager = CustomPermission.objects.create(
        name='Can create manager', codename='can_create_manager'
    )

    # Дозволи для роботи з оголошеннями
    can_create_listing = CustomPermission.objects.create(
        name='Can create listing', codename='can_create_listing'
    )
    can_view_own_listings = CustomPermission.objects.create(
        name='Can view own listing', codename='can_view_own_listings'
    )
    can_update_own_listing = CustomPermission.objects.create(
        name='Can update own listing', codename='can_update_own_listing'
    )
    can_delete_own_listing = CustomPermission.objects.create(
        name='Can delete own listing', codename='can_delete_own_listing'
    )
    can_upload_own_images = CustomPermission.objects.create(
        name='Can upload own listing', codename='can_upload_own_images'
    )
    can_delete_own_images = CustomPermission.objects.create(
        name='Can delete own images', codename='can_delete_own_images'
    )
    can_edit_listings = CustomPermission.objects.create(
        name='Can edit listings', codename='can_edit_listings'
    )
    can_moderate_listings = CustomPermission.objects.create(
        name='Can moderate listings', codename='can_moderate_listings'
    )

    # Дозволи для статистики та автомобілів
    can_view_statistics = CustomPermission.objects.create(
        name='Can view statistic', codename='can_view_statistics'
    )
    can_add_car_models = CustomPermission.objects.create(
        name='Can add car models', codename='can_add_car_models'
    )
    can_update_delete_car_models = CustomPermission.objects.create(
        name='Can update or delete car models', codename='can_update_delete_car_models'
    )
    can_add_brands = CustomPermission.objects.create(
        name='Can add brands', codename='can_add_brands'
    )
    can_update_delete_brands = CustomPermission.objects.create(
        name='Can update or delete brands', codename='can_update_delete_brands'
    )

    # ==================== РОЛІ ====================
    buyer = Role.objects.create(name='buyer')
    seller = Role.objects.create(name='seller')
    manager = Role.objects.create(name='manager')
    admin = Role.objects.create(name='admin')

    # ==================== ПРИЗНАЧЕННЯ ДОЗВОЛІВ РОЛЯМ ====================

    # Покупець: базові можливості
    buyer_permissions = [
        can_create_listing,
        can_be_premium_user,
        can_view_own_account,
        can_update_own_account,
        can_delete_own_account
    ]
    for permission in buyer_permissions:
        RolePermissions.objects.create(role=buyer, permission=permission)

    # Продавець: повне управління власними оголошеннями
    seller_permissions = [
        can_create_listing,
        can_view_own_listings,
        can_update_own_listing,
        can_delete_own_listing,
        can_upload_own_images,
        can_delete_own_images,
        can_view_statistics,
        can_be_premium_user,
        can_view_own_account,
        can_update_own_account,
        can_delete_own_account
    ]
    for permission in seller_permissions:
        RolePermissions.objects.create(role=seller, permission=permission)

    # Менеджер: модерація та управління користувачами
    manager_permissions = [
        can_edit_listings,
        can_moderate_listings,
        can_add_brands,
        can_add_car_models,
        can_view_own_account,
        can_view_statistics,
        can_view_users,
        can_view_user_by_id,
        can_delete_user_by_id,
        can_block_unblock_user,
        can_update_own_account
    ]
    for permission in manager_permissions:
        RolePermissions.objects.create(role=manager, permission=permission)

    # Адміністратор: повний доступ
    admin_permissions = [
        can_edit_listings,
        can_moderate_listings,
        can_add_brands,
        can_update_delete_brands,
        can_add_car_models,
        can_update_delete_car_models,
        can_view_own_account,
        can_update_own_account,
        can_delete_own_account,
        can_view_statistics,
        can_view_users,
        can_view_user_by_id,
        can_delete_user_by_id,
        can_block_unblock_user,
        can_create_manager
    ]
    for permission in admin_permissions:
        RolePermissions.objects.create(role=admin, permission=permission)


def reverse_seed(apps, schema_editor):
    """Відкатує міграцію - видаляє всі ролі та дозволи."""
    Role = apps.get_model('users', 'Role')
    CustomPermission = apps.get_model('users', 'CustomPermission')
    Role.objects.all().delete()
    CustomPermission.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_roles_and_permissions, reverse_seed)
    ]