# Generated by Django 6.1.1 on 2026-09-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('usd_to_uah', models.DecimalField(decimal_places=4, max_digits=10)),
                ('eur_to_uah', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'currency_rate',
                'ordering': ['-date'],
            },
        ),
    ]
